### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method RWMB_Field::process_value() 

### ISSUE THREAD

**Issue by socrates77** [wpmetabox/mb-rest-api#13]
When I try to post and save a CPT with a custom field managed with Meta Box I get this error.
`FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method RWMB_Field::process_value() in /var/www/html/wp-content/plugins/mb-rest-api/class-mb-rest-api.php:221
web_1         | Stack trace:
web_1         | #0 /var/www/html/wp-content/plugins/mb-rest-api/class-mb-rest-api.php(113): MB_Rest_API->update_value(Array, 1, 82818)
web_1         | #1 /var/www/html/wp-includes/rest-api/endpoints/class-wp-rest-controller.php(461): MB_Rest_API->update_post_meta(Array, Object(WP_Post), 'meta_box', Object(WP_REST_Request), 'familygo_offert...')
web_1         | #2 /var/www/html/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php(659): WP_REST_Controller->update_additional_fields_for_object(Object(WP_Post), Object(WP_REST_Request))
web_1         | #3 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(1050): WP_REST_Posts_Controller->create_item(Object(WP_REST_Request))
web_1         | #4 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(376): WP_REST_Server->dispatch(Object(WP_REST_Request))
web_1         | #5 /var/www/html/wp-includes/rest-api.php(339): WP_REST_Server->serve_request('/wp/v2/offerta')
web_1         | #6 /var/www/html/w in /var/www/html/wp-content/plugins/mb-rest-api/class-mb-rest-api.php on line 221`

WordPress 5.5.3
MB Rest API 1.4.0
Meta Box 4.18.4

PHP 7.4

**Comment by socrates77** [comment]
I've updated Meta Box to the last release and the problem solved
